name: Deploy to sandbox on pull request label

on:
  pull_request:
    types: [labeled]

concurrency: 
  group: dsb-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: 
  id-token: write
  contents: read
  pull-requests: write

jobs:

  Build:
    if: contains(github.event.pull_request.labels.*.name, 'deploy-sandbox')   
    uses: ./.github/workflows/rwf-build-upload-package.yml

  DeployToSandbox:
    name: Deploy to sandbox
    needs:
    - Build    
    uses: ./.github/workflows/rwf-deploy-azure-webapp.yml
    with:
        env: Sandbox
        web-app-name: saf-sandbox-python-flask
    secrets: 
        publish-profile: "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SANDBOX }}"

  AddPrComment:    
    name: PR comment
    runs-on: ubuntu-latest
    needs: DeployToSandbox
    if: success()
    steps:
      - name: Add comment to pull request
        run: |
          echo "Deployed to sandbox at https://saf-sandbox-python-flask.azurewebsites.net/" > comment.txt
          gh pr comment $PR_URL --body "$(cat comment.txt)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}


